language: node_js

node_js:
  - "node"
  - "6"

env:
  - NG_VERSION=4 TS_VERSION=2.3.4 MAT_VERSION=2.0.0-beta.12
  - NG_VERSION=5 TS_VERSION=2.5.3 MAT_VERSION=5

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - "npm install -g @angular/cli"
  - "npm install @angular/common@${NG_VERSION} @angular/core@${NG_VERSION} @angular/forms@${NG_VERSION}"
  - "npm install @angular/http@${NG_VERSION} @angular/platform-browser@${NG_VERSION} @angular/platform-browser-dynamic@${NG_VERSION}"
  - "npm install @angular/compiler@${NG_VERSION} @angular/compiler-cli@${NG_VERSION}"
  - "npm install @angular/animations@${NG_VERSION} @angular/cdk@${MAT_VERSION} @angular/material@${MAT_VERSION}"
  - "npm install typescript@${TS_VERSION}"
  - "npm install"

script:
  - npm run build
  - npm run test:once
  - npm run cleardown
  - npm run send
